---
- name: show version and other user level commands
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - show ip int brief


      register: print_output

    -  debug: var=print_output.stdout_lines