---
- name: Manage GNS3 devices
  hosts: R1
  gather_facts: false
  connection: local

  vars:
    cli:
      username: username
      password: cisco
      transport: cli

  tasks:
    - name: enable ospf
      ios_confi:
        provider: "{{cli}}"
        authorize: yes
        parents: router ospf 1
        lines: 
          - network 0.0.0.0 255.255.255.255 area 0

        register: print_output

    - debug: var=print_output 

    